name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'gradle'

      - name: Run tests (headless)
        run: ./gradlew test -Dheadless=true

      # Upload Allure results (raw) as an artifact
      - name: Upload allure-results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: build/allure-results

      # Also upload JUnit XML for quick inspection (optional)
      - name: Upload test reports (JUnit XML / Gradle)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: junit-and-gradle-reports
          path: |
            build/test-results/test
            build/reports/tests/test
